FROM node:latest
EXPOSE 90
COPY package.json package.json
RUN npm install
COPY app.js app.js
COPY config/ config/
COPY lib/ lib/
COPY web/ web/
CMD node app.js --config-prefix demo.west.,demo.all. --instance west-1 --log-level verbose